package: bootstrap_helper
version: '0.1.5.5'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/bootstrap_helper/issues
info: 'Idee und Realisierung der ersten Version: Oliver Kreischer / concedra.de'
compile: 0

page:
    title: 'translate:title'
    perm: bootstrap_helper[]
    icon: rex-icon fa-bold
    subpages:
        info:
          title: 'translate:general'
          subpages:
              info:
                title: 'translate:info'
          #   moduluebersicht: { title: 'translate:moduluebersicht'}
          #   templateuebersicht: { title: 'translate:templateuebersicht'}
              roadmap:
                title: 'translate:roadmap'
              changelog:
                title: 'translate:changelog'
              license:
                title: 'translate:license'
        module:
          title: 'translate:module'
        templates:
          title: 'translate:templates'
        snippets:
          title: 'translate:snippets'

requires:
    packages:
        mform: '^5.1.0'
        mblock: '^2.1.0'
    redaxo: '^5.3.0'

